websites = {
    "google": "https://www.google.com",
    "bing": "https://www.bing.com",
    "yahoo": "https://www.yahoo.com",
    "duckduckgo": "https://duckduckgo.com",
    "baidu": "https://www.baidu.com",
    "yandex": "https://yandex.com",
    "ask": "https://www.ask.com",
    "ecosia": "https://www.ecosia.org",
    "wikipedia": "https://www.wikipedia.org/",
    "wikihow": "https://www.wikihow.com",
    "archive": "https://archive.org",
    "gmail": "https://mail.google.com/",
    "outlook": "https://outlook.live.com",
    "yahoo mail": "https://mail.yahoo.com",
    "protonmail": "https://mail.proton.me",
    "google drive": "https://drive.google.com",
    "google docs": "https://docs.google.com",
    "google sheets": "https://sheets.google.com",
    "google slides": "https://slides.google.com",
    "google calendar": "https://calendar.google.com",
    "google keep": "https://keep.google.com",
    "google photos": "https://photos.google.com",
    "google maps": "https://maps.google.com",
    "google translate": "https://translate.google.com",
    "onedrive": "https://onedrive.live.com",
    "dropbox": "https://www.dropbox.com",
    "box": "https://www.box.com",
    "notion": "https://www.notion.so",
    "evernote": "https://evernote.com",
    "trello": "https://trello.com",
    "asana": "https://asana.com",
    "monday": "https://monday.com",
    "clickup": "https://clickup.com",
    "slack": "https://slack.com",
    "zoom": "https://zoom.us",
    "microsoft teams": "https://www.microsoft.com/microsoft-teams",
    "google meet": "https://meet.google.com",
    "calendly": "https://calendly.com",
    "airtable": "https://airtable.com",
    "todoist": "https://todoist.com",
    "canva": "https://canva.com",
    "figma": "https://www.figma.com",
    "miro": "https://miro.com",
    "loom": "https://www.loom.com",
    "grammarly": "https://www.grammarly.com",
    "docusign": "https://www.docusign.com",
    "adobe": "https://www.adobe.com",
    "wetransfer": "https://wetransfer.com",
    "lastpass": "https://www.lastpass.com",
    "1password": "https://1password.com",
    "bitwarden": "https://bitwarden.com",
     "facebook": "https://www.facebook.com",
    "twitter": "https://www.twitter.com",
    "x": "https://x.com",
    "instagram": "https://www.instagram.com",
    "tiktok": "https://tiktok.com",
    "snapchat": "https://www.snapchat.com",
    "pinterest": "https://www.pinterest.com",
    "linkedin": "https://www.linkedin.com",
    "reddit": "https://www.reddit.com",
    "tumblr": "https://www.tumblr.com",
    "whatsapp": "https://web.whatsapp.com",
    "telegram": "https://web.telegram.org",
    "discord": "https://discord.com",
    "wechat": "https://www.wechat.com",
    "line": "https://line.me",
    "vk": "https://vk.com",
    "weibo": "https://weibo.com",
    "quora": "https://www.quora.com",
    "medium": "https://medium.com",
    "mastodon": "https://mastodon.social",
    "threads": "https://www.threads.net",
    "bereal": "https://bere.al",
    "clubhouse": "https://www.clubhouse.com",
    "nextdoor": "https://nextdoor.com",
    "meetup": "https://www.meetup.com",
    "myspace": "https://myspace.com",
    "flickr": "https://www.flickr.com",
    "imgur": "https://imgur.com",
    "9gag": "https://9gag.com",
    "tinder": "https://tinder.com",
    "bumble": "https://bumble.com",
    "hinge": "https://hinge.co",
    "okcupid": "https://www.okcupid.com",
    "youtube": "https://www.youtube.com",
    "netflix": "https://www.netflix.com",
    "hulu": "https://www.hulu.com",
    "disney plus": "https://www.disneyplus.com",
    "amazon prime video": "https://www.primevideo.com",
    "hbo max": "https://www.max.com",
    "max": "https://www.max.com",
    "apple tv": "https://tv.apple.com",
    "peacock": "https://www.peacocktv.com",
    "paramount plus": "https://www.paramountplus.com",
    "crunchyroll": "https://www.crunchyroll.com",
    "twitch": "https://www.twitch.tv",
    "vimeo": "https://vimeo.com",
    "dailymotion": "https://www.dailymotion.com",
    "spotify": "https://open.spotify.com/",
    "apple music": "https://music.apple.com",
    "soundcloud": "https://soundcloud.com",
    "pandora": "https://www.pandora.com",
    "tidal": "https://tidal.com",
    "deezer": "https://www.deezer.com",
    "bandcamp": "https://bandcamp.com",
    "shazam": "https://www.shazam.com",
    "genius": "https://genius.com",
    "iheartradio": "https://www.iheart.com",
    "audible": "https://www.audible.com",
    "bilibili": "https://www.bilibili.tv",
    "vudu": "https://www.vudu.com",
    "plex": "https://www.plex.tv",
    "kanopy": "https://www.kanopy.com",
    "tubi": "https://tubitv.com",
    "pluto tv": "https://pluto.tv",
    "curiositystream": "https://curiositystream.com",
    "mubi": "https://mubi.com",
    "letterboxd": "https://letterboxd.com",
    "imdb": "https://www.imdb.com",
    "rotten tomatoes": "https://www.rottentomatoes.com",
    "metacritic": "https://www.metacritic.com",
     "amazon": "https://www.amazon.com",
    "ebay": "https://www.ebay.com",
    "walmart": "https://www.walmart.com",
    "target": "https://www.target.com",
    "best buy": "https://www.bestbuy.com",
    "costco": "https://www.costco.com",
    "aliexpress": "https://www.aliexpress.com",
    "alibaba": "https://www.alibaba.com",
    "etsy": "https://www.etsy.com",
    "shopify": "https://www.shopify.com",
    "wish": "https://www.wish.com",
    "wayfair": "https://www.wayfair.com",
    "ikea": "https://www.ikea.com",
    "home depot": "https://www.homedepot.com",
    "lowes": "https://www.lowes.com",
    "zara": "https://www.zara.com",
    "hm": "https://www2.hm.com",
    "nike": "https://www.nike.com",
    "adidas": "https://www.adidas.com",
    "asos": "https://www.asos.com",
    "shein": "https://www.shein.com",
    "macys": "https://www.macys.com",
    "nordstrom": "https://www.nordstrom.com",
    "sephora": "https://www.sephora.com",
    "ulta": "https://www.ulta.com",
    "chewy": "https://www.chewy.com",
    "newegg": "https://www.newegg.com",
    "overstock": "https://www.overstock.com",
    "flipkart": "https://www.flipkart.com",
    "daraz": "https://www.daraz.pk",
    "temu": "https://www.temu.com",
    "poshmark": "https://poshmark.com",
    "depop": "https://www.depop.com",
    "mercari": "https://www.mercari.com",
    "craigslist": "https://www.craigslist.org",
    "facebook marketplace": "https://www.facebook.com/marketplace",
    "groupon": "https://www.groupon.com",
    "rakuten": "https://www.rakuten.com",
    "zappos": "https://www.zappos.com",
    "gap": "https://www.gap.com",
    "uniqlo": "https://www.uniqlo.com",
    "victoria's secret": "https://www.victoriassecret.com",
    "ashley furniture": "https://www.ashleyfurniture.com",
    "github": "https://www.github.com/",
    "gitlab": "https://gitlab.com",
    "bitbucket": "https://bitbucket.org",
    "stackoverflow": "https://stackoverflow.com",
    "stack exchange": "https://stackexchange.com",
    "npm": "https://www.npmjs.com",
    "pypi": "https://pypi.org",
    "docker": "https://www.docker.com",
    "dockerhub": "https://hub.docker.com",
    "kubernetes": "https://kubernetes.io",
    "aws": "https://aws.amazon.com",
    "azure": "https://azure.microsoft.com",
    "google cloud": "https://cloud.google.com",
    "digitalocean": "https://www.digitalocean.com",
    "heroku": "https://www.heroku.com",
    "vercel": "https://vercel.com",
    "netlify": "https://www.netlify.com",
    "cloudflare": "https://www.cloudflare.com",
    "godaddy": "https://www.godaddy.com",
    "namecheap": "https://www.namecheap.com",
    "hostinger": "https://www.hostinger.com",
    "wordpress": "https://wordpress.com",
    "wix": "https://www.wix.com",
    "squarespace": "https://www.squarespace.com",
    "webflow": "https://webflow.com",
    "replit": "https://replit.com",
    "codepen": "https://codepen.io",
    "jsfiddle": "https://jsfiddle.net",
    "leetcode": "https://leetcode.com",
    "hackerrank": "https://www.hackerrank.com",
    "codeforces": "https://codeforces.com",
    "kaggle": "https://www.kaggle.com",
    "huggingface": "https://huggingface.co",
    "producthunt": "https://www.producthunt.com",
    "hacker news": "https://news.ycombinator.com",
    "dev.to": "https://dev.to",
    "hashnode": "https://hashnode.com",
    "w3schools": "https://www.w3schools.com",
    "mdn": "https://developer.mozilla.org",
    "geeksforgeeks": "https://www.geeksforgeeks.org",
    "freecodecamp": "https://www.freecodecamp.org",
    "codecademy": "https://www.codecademy.com",
    "jetbrains": "https://www.jetbrains.com",
    "visual studio": "https://visualstudio.microsoft.com",
    "sourceforge": "https://sourceforge.net",
    "postman": "https://www.postman.com",
    "jira": "https://www.atlassian.com/software/jira",
    "confluence": "https://www.atlassian.com/software/confluence",
    "salesforce": "https://www.salesforce.com",
    "zendesk": "https://www.zendesk.com",
    "hubspot": "https://www.hubspot.com",
    "mailchimp": "https://mailchimp.com",
     "chatgpt": "https://chatgpt.com/",
    "claude": "https://claude.ai",
    "gemini": "https://gemini.google.com",
    "meta ai": "https://meta.ai",
    "copilot": "https://copilot.microsoft.com",
    "perplexity": "https://www.perplexity.ai",
    "midjourney": "https://www.midjourney.com",
    "dall-e": "https://openai.com/dall-e-2",
    "stable diffusion": "https://stability.ai",
    "runwayml": "https://runwayml.com",
    "character.ai": "https://character.ai",
    "poe": "https://poe.com",
    "openai": "https://openai.com",
    "deepseek": "https://www.deepseek.com",
    "grok": "https://grok.x.ai",
    "you.com": "https://you.com",
    "leonardo ai": "https://leonardo.ai",
    "elevenlabs": "https://elevenlabs.io",
    "synthesia": "https://www.synthesia.io",
    "notion ai": "https://www.notion.so/product/ai",
     "cnn": "https://www.cnn.com",
    "bbc": "https://www.bbc.com",
    "fox news": "https://www.foxnews.com",
    "nbc news": "https://www.nbcnews.com",
    "abc news": "https://abcnews.go.com",
    "cbs news": "https://www.cbsnews.com",
    "reuters": "https://www.reuters.com",
    "associated press": "https://apnews.com",
    "the guardian": "https://www.theguardian.com",
    "new york times": "https://www.nytimes.com",
    "washington post": "https://www.washingtonpost.com",
    "wall street journal": "https://www.wsj.com",
    "usa today": "https://www.usatoday.com",
    "al jazeera": "https://www.aljazeera.com",
    "bloomberg": "https://www.bloomberg.com",
    "cnbc": "https://www.cnbc.com",
    "forbes": "https://www.forbes.com",
    "time": "https://time.com",
    "the economist": "https://www.economist.com",
    "npr": "https://www.npr.org",
    "politico": "https://www.politico.com",
    "the hill": "https://thehill.com",
    "huffpost": "https://www.huffpost.com",
    "vox": "https://www.vox.com",
    "buzzfeed": "https://www.buzzfeed.com",
    "vice": "https://www.vice.com",
    "the verge": "https://www.theverge.com",
    "techcrunch": "https://techcrunch.com",
    "engadget": "https://www.engadget.com",
    "wired": "https://www.wired.com",
    "ars technica": "https://arstechnica.com",
    "gizmodo": "https://gizmodo.com",
    "mashable": "https://mashable.com",
    "cnet": "https://www.cnet.com",
    "dawn": "https://www.dawn.com",
    "geo news": "https://www.geo.tv",
    "the express tribune": "https://tribune.com.pk",
    "ary news": "https://arynews.tv",
    "hindustan times": "https://www.hindustantimes.com",
    "times of india": "https://timesofindia.indiatimes.com",
    "ndtv": "https://www.ndtv.com",
     "paypal": "https://www.paypal.com",
    "stripe": "https://stripe.com",
    "venmo": "https://venmo.com",
    "cash app": "https://cash.app",
    "wise": "https://wise.com",
    "revolut": "https://www.revolut.com",
    "chase": "https://www.chase.com",
    "bank of america": "https://www.bankofamerica.com",
    "wells fargo": "https://www.wellsfargo.com",
    "capital one": "https://www.capitalone.com",
    "american express": "https://www.americanexpress.com",
    "coinbase": "https://www.coinbase.com",
    "binance": "https://www.binance.com",
    "kraken": "https://www.kraken.com",
    "robinhood": "https://robinhood.com",
    "etrade": "https://www.etrade.com",
    "fidelity": "https://www.fidelity.com",
    "vanguard": "https://www.vanguard.com",
    "charles schwab": "https://www.schwab.com",
    "mint": "https://mint.intuit.com",
    "nerdwallet": "https://www.nerdwallet.com",
    "credit karma": "https://www.creditkarma.com",
    "turbotax": "https://turbotax.intuit.com",
    "quickbooks": "https://quickbooks.intuit.com",
    "coingecko": "https://www.coingecko.com",
    "coinmarketcap": "https://coinmarketcap.com",
     "booking.com": "https://www.booking.com",
    "airbnb": "https://www.airbnb.com",
    "expedia": "https://www.expedia.com",
    "tripadvisor": "https://www.tripadvisor.com",
    "kayak": "https://www.kayak.com",
    "skyscanner": "https://www.skyscanner.com",
    "hotels.com": "https://www.hotels.com",
    "agoda": "https://www.agoda.com",
    "trivago": "https://www.trivago.com",
    "vrbo": "https://www.vrbo.com",
    "priceline": "https://www.priceline.com",
    "google flights": "https://www.google.com/travel/flights",
    "uber": "https://www.uber.com",
    "lyft": "https://www.lyft.com",
    "careem": "https://www.careem.com",
    "emirates": "https://www.emirates.com",
    "qatar airways": "https://www.qatarairways.com",
    "pia": "https://www.piac.com.pk",
    "turkish airlines": "https://www.turkishairlines.com",
    "delta": "https://www.delta.com",
    "united airlines": "https://www.united.com",
    "american airlines": "https://www.aa.com",
    "southwest": "https://www.southwest.com",
    "ryanair": "https://www.ryanair.com",
    "easyjet": "https://www.easyjet.com",
    "uber eats": "https://www.ubereats.com",
    "doordash": "https://www.doordash.com",
    "grubhub": "https://www.grubhub.com",
    "postmates": "https://postmates.com",
    "deliveroo": "https://deliveroo.com",
    "foodpanda": "https://www.foodpanda.com",
    "zomato": "https://www.zomato.com",
    "swiggy": "https://www.swiggy.com",
    "yelp": "https://www.yelp.com",
    "opentable": "https://www.opentable.com",
    "allrecipes": "https://www.allrecipes.com",
    "food network": "https://www.foodnetwork.com",
    "epicurious": "https://www.epicurious.com",
    "mcdonalds": "https://www.mcdonalds.com",
    "starbucks": "https://www.starbucks.com",
    "dominos": "https://www.dominos.com",
    "pizza hut": "https://www.pizzahut.com",
    "kfc": "https://www.kfc.com",
    "subway": "https://www.subway.com",
    "chick-fil-a": "https://www.chick-fil-a.com",
    "coursera": "https://www.coursera.org",
    "udemy": "https://www.udemy.com",
    "edx": "https://www.edx.org",
    "khan academy": "https://www.khanacademy.org",
    "udacity": "https://www.udacity.com",
    "skillshare": "https://www.skillshare.com",
    "duolingo": "https://www.duolingo.com",
    "chegg": "https://www.chegg.com",
    "quizlet": "https://quizlet.com",
    "brainly": "https://brainly.com",
    "researchgate": "https://www.researchgate.net",
    "google scholar": "https://scholar.google.com",
    "jstor": "https://www.jstor.org",
    "sci-hub": "https://sci-hub.se",
    "coursehero": "https://www.coursehero.com",
    "masterclass": "https://www.masterclass.com",
    "linkedin learning": "https://www.linkedin.com/learning",
    "pluralsight": "https://www.pluralsight.com",
    "codewars": "https://www.codewars.com",
    "britannica": "https://www.britannica.com",
    "dictionary.com": "https://www.dictionary.com",
    "merriam-webster": "https://www.merriam-webster.com",
    "thesaurus.com": "https://www.thesaurus.com",
    "grammarbook": "https://www.grammarbook.com",
    "purdue owl": "https://owl.purdue.edu",
     "nadra": "https://www.nadra.gov.pk",
    "fbr": "https://www.fbr.gov.pk",
    "hec": "https://www.hec.gov.pk",
    "pakistan railways": "https://www.pakrail.gov.pk",
    "sbp": "https://www.sbp.org.pk",
    "peca": "https://www.pta.gov.pk",
    "usa.gov": "https://www.usa.gov",
    "irs": "https://www.irs.gov",
    "un": "https://www.un.org",
    "world bank": "https://www.worldbank.org",
    "imf": "https://www.imf.org",
    "nasa": "https://www.nasa.gov",
    "cdc": "https://www.cdc.gov",
    "fda": "https://www.fda.gov",
    "gov.uk": "https://www.gov.uk",
    "espn": "https://www.espn.com",
    "nba": "https://www.nba.com",
    "nfl": "https://www.nfl.com",
    "fifa": "https://www.fifa.com",
    "uefa": "https://www.uefa.com",
    "premier league": "https://www.premierleague.com",
    "cricbuzz": "https://www.cricbuzz.com",
    "espn cricinfo": "https://www.espncricinfo.com",
    "icc cricket": "https://www.icc-cricket.com",
    "olympics": "https://olympics.com",
    "goal.com": "https://www.goal.com",
    "bleacher report": "https://bleacherreport.com",
    "sky sports": "https://www.skysports.com",
    "formula 1": "https://www.formula1.com",
    "ufc": "https://www.ufc.com",
    "wwe": "https://www.wwe.com",
     "steam": "https://store.steampowered.com",
    "epic games": "https://www.epicgames.com",
    "playstation": "https://www.playstation.com",
    "xbox": "https://www.xbox.com",
    "nintendo": "https://www.nintendo.com",
    "ea": "https://www.ea.com",
    "ubisoft": "https://www.ubisoft.com",
    "itch.io": "https://itch.io",
    "gog": "https://www.gog.com",
    "roblox": "https://www.roblox.com",
    "minecraft": "https://www.minecraft.net",
    "fortnite": "https://www.fortnite.com",
    "ign": "https://www.ign.com",
    "gamespot": "https://www.gamespot.com",
    "polygon": "https://www.polygon.com",
    "kotaku": "https://kotaku.com",
    "battle.net": "https://www.battle.net",
    "riot games": "https://www.riotgames.com",
    "chess.com": "https://www.chess.com",
    "lichess": "https://lichess.org",
    "4chan": "https://www.4chan.org",
    "digg": "https://digg.com",
    "slashdot": "https://slashdot.org",
    "metafilter": "https://www.metafilter.com",
    "goodreads": "https://www.goodreads.com",
    "deviantart": "https://www.deviantart.com",
    "behance": "https://www.behance.net",
    "dribbble": "https://dribbble.com",
    "500px": "https://500px.com",
    "unsplash": "https://unsplash.com",
    "pexels": "https://www.pexels.com",
    "pixabay": "https://pixabay.com",
    "giphy": "https://giphy.com",
    "archive of our own": "https://archiveofourown.org",
    "wattpad": "https://www.wattpad.com",
    "fanfiction.net": "https://www.fanfiction.net",
    "weather.com": "https://weather.com",
    "accuweather": "https://www.accuweather.com",
    "speedtest": "https://www.speedtest.net",
    "virustotal": "https://www.virustotal.com",
    "whatismyip": "https://www.whatismyip.com",
    "shorturl": "https://www.shorturl.at",
    "bit.ly": "https://bitly.com",
    "tinyurl": "https://tinyurl.com",
    "qr code generator": "https://www.qr-code-generator.com",
    "canva print": "https://www.canva.com/print",
    "meetup.com": "https://www.meetup.com",
    "eventbrite": "https://www.eventbrite.com",
    "ticketmaster": "https://www.ticketmaster.com",
    "stubhub": "https://www.stubhub.com",
    "zillow": "https://www.zillow.com",
    "realtor.com": "https://www.realtor.com",
    "redfin": "https://www.redfin.com",
    "indeed": "https://www.indeed.com",
    "glassdoor": "https://www.glassdoor.com",
    "monster": "https://www.monster.com",
    "ziprecruiter": "https://www.ziprecruiter.com",
    "rozee.pk": "https://www.rozee.pk",
    "upwork": "https://www.upwork.com",
    "fiverr": "https://www.fiverr.com",
    "freelancer": "https://www.freelancer.com",
    "toptal": "https://www.toptal.com",
    "angellist": "https://angel.co",
    "crunchbase": "https://www.crunchbase.com",
    "yelp business": "https://biz.yelp.com",
    "trustpilot": "https://www.trustpilot.com",
    "consumer reports": "https://www.consumerreports.org",
    "wirecutter": "https://www.nytimes.com/wirecutter",
    "webmd": "https://www.webmd.com",
    "mayo clinic": "https://www.mayoclinic.org",
    "healthline": "https://www.healthline.com",
    "drugs.com": "https://www.drugs.com",
    "marham": "https://www.marham.pk",
    "oladoc": "https://oladoc.com",
    "petsmart": "https://www.petsmart.com",
    "chess24": "https://chess24.com",
    "duolingo english test": "https://englishtest.duolingo.com",
    "libgen": "https://libgen.is",
    "z-library": "https://z-lib.io",
    "openlibrary": "https://openlibrary.org",
    "gutenberg project": "https://www.gutenberg.org",
    "internet archive": "https://archive.org",
    "wayback machine": "https://web.archive.org",
    "reddit enhancement": "https://redditenhancementsuite.com",
    "producthunt daily": "https://www.producthunt.com/topics/today",
    "hackaday": "https://hackaday.com",
    "instructables": "https://www.instructables.com",
    "thingiverse": "https://www.thingiverse.com",
    "shapeways": "https://www.shapeways.com",
    "etsy sellers": "https://www.etsy.com/sell",
    "shutterstock": "https://www.shutterstock.com",
    "istockphoto": "https://www.istockphoto.com",
    "gettyimages": "https://www.gettyimages.com",
    "canva templates": "https://www.canva.com/templates",
    "adobe stock": "https://stock.adobe.com",
    "envato": "https://envato.com",
    "themeforest": "https://themeforest.net",
    "codecanyon": "https://codecanyon.net",
    "graphicriver": "https://graphicriver.net",
    "audiojungle": "https://audiojungle.net",
    "videohive": "https://videohive.net",
    "flaticon": "https://www.flaticon.com",
    "iconfinder": "https://www.iconfinder.com",
    "fontawesome": "https://fontawesome.com",
    "google fonts": "https://fonts.google.com",
    "dafont": "https://www.dafont.com",
    "coolors": "https://coolors.co",
    "colorhunt": "https://colorhunt.co",
    "material design": "https://m3.material.io",
    "tailwindcss": "https://tailwindcss.com",
    "bootstrap": "https://getbootstrap.com",
    "caniuse": "https://caniuse.com",
    "regex101": "https://regex101.com",
    "jsonformatter": "https://jsonformatter.org",
    "base64 decode": "https://www.base64decode.org",
    "diffchecker": "https://www.diffchecker.com",
    "carbon": "https://carbon.now.sh",
    "excalidraw": "https://excalidraw.com",
    "drawio": "https://app.diagrams.net",
    "lucidchart": "https://www.lucidchart.com",
    "obsidian": "https://obsidian.md",
    "roam research": "https://roamresearch.com",
    "logseq": "https://logseq.com",
    "anki": "https://apps.ankiweb.net",
    "duolingo abc": "https://www.duolingo.com/abc",
    "babbel": "https://www.babbel.com",
    "busuu": "https://www.busuu.com",
    "italki": "https://www.italki.com",
    "preply": "https://preply.com",
    "wyzant": "https://www.wyzant.com",
    "vipkid": "https://www.vipkid.com",
    "outschool": "https://outschool.com",
    "codesignal": "https://codesignal.com",
    "topcoder": "https://www.topcoder.com",
    "exercism": "https://exercism.org",
    "codewars practice": "https://www.codewars.com/dashboard",
    "devpost": "https://devpost.com",
    "kaggle competitions": "https://www.kaggle.com/competitions",
    "papers with code": "https://paperswithcode.com",
    "arxiv": "https://arxiv.org",
    "semantic scholar": "https://www.semanticscholar.org",
    "connected papers": "https://www.connectedpapers.com",
    "overleaf": "https://www.overleaf.com",
    "zotero": "https://www.zotero.org",
    "mendeley": "https://www.mendeley.com",
    "researchsquare": "https://www.researchsquare.com",
    "biorxiv": "https://www.biorxiv.org",
    "medrxiv": "https://www.medrxiv.org",
    "ssrn": "https://www.ssrn.com",
    "plos": "https://plos.org",
    "nature": "https://www.nature.com",
    "science.org": "https://www.science.org",
    "sciencedirect": "https://www.sciencedirect.com",
    "springer": "https://link.springer.com",
    "wiley": "https://onlinelibrary.wiley.com",
    "ieee": "https://www.ieee.org",
    "acm digital library": "https://dl.acm.org",
    "cambridge core": "https://www.cambridge.org/core",
    "oxford academic": "https://academic.oup.com",
    "pubmed": "https://pubmed.ncbi.nlm.nih.gov",
    "clinicaltrials.gov": "https://clinicaltrials.gov",
    "cochrane library": "https://www.cochranelibrary.com",
    "uptodate": "https://www.uptodate.com",
    "medscape": "https://www.medscape.com",
    "rxlist": "https://www.rxlist.com",
    "goodrx": "https://www.goodrx.com",
    "1mg": "https://www.1mg.com",
    "practo": "https://www.practo.com",
    "sehat kahani": "https://sehatkahani.com",
    "daraz mall": "https://www.daraz.pk/malls",
    "pakwheels": "https://www.pakwheels.com",
    "olx": "https://www.olx.com",
    "olx pakistan": "https://www.olx.com.pk",
    "zameen": "https://www.zameen.com",
    "graana": "https://graana.com",
    "carfirst": "https://carfirst.pk",
    "autotrader": "https://www.autotrader.com",
    "cars.com": "https://www.cars.com",
    "kbb": "https://www.kbb.com",
    "edmunds": "https://www.edmunds.com",
    "carmax": "https://www.carmax.com",
    "vroom": "https://www.vroom.com",
    "carvana": "https://www.carvana.com",
    "tesla": "https://www.tesla.com",
    "ford": "https://www.ford.com",
    "toyota": "https://www.toyota.com",
    "honda": "https://www.honda.com",
    "bmw": "https://www.bmw.com",
    "mercedes-benz": "https://www.mercedes-benz.com",
    "audi": "https://www.audi.com",
    "volkswagen": "https://www.vw.com",
    "hyundai": "https://www.hyundai.com",
    "kia": "https://www.kia.com",
    "suzuki pakistan": "https://www.paksuzuki.com.pk",
    "toyota indus": "https://www.toyota-indus.com",
    "mg motor pakistan": "https://www.mgmotor.com.pk",
    "apple": "https://www.apple.com",
    "samsung": "https://www.samsung.com",
    "sony": "https://www.sony.com",
    "lg": "https://www.lg.com",
    "microsoft": "https://microsoft.com",
    "dell": "https://www.dell.com",
    "hp": "https://www.hp.com",
    "lenovo": "https://www.lenovo.com",
    "asus": "https://www.asus.com",
    "acer": "https://www.acer.com",
    "msi": "https://www.msi.com",
    "razer": "https://www.razer.com",
    "logitech": "https://www.logitech.com",
    "corsair": "https://www.corsair.com",
    "nvidia": "https://www.nvidia.com",
    "amd": "https://www.amd.com",
    "intel": "https://www.intel.com",
    "qualcomm": "https://www.qualcomm.com",
    "xiaomi": "https://www.mi.com",
    "oneplus": "https://www.oneplus.com",
    "huawei": "https://www.huawei.com",
    "oppo": "https://www.oppo.com",
    "vivo": "https://www.vivo.com",
    "realme": "https://www.realme.com",
    "gsmarena": "https://www.gsmarena.com",
    "androidauthority": "https://www.androidauthority.com",
    "9to5mac": "https://9to5mac.com",
    "macrumors": "https://www.macrumors.com",
    "xda developers": "https://www.xda-developers.com",
    "tomshardware": "https://www.tomshardware.com",
    "anandtech": "https://www.anandtech.com",
    "pcmag": "https://www.pcmag.com",
    "digitaltrends": "https://www.digitaltrends.com",
    "slickdeals": "https://slickdeals.net",
    "retailmenot": "https://www.retailmenot.com",
    "honey": "https://www.joinhoney.com",
    "camelcamelcamel": "https://camelcamelcamel.com",
    "keepa": "https://keepa.com",
    "priceline pk": "https://www.priceoye.pk",
    "priceoye": "https://priceoye.pk",
    "telemart": "https://telemart.pk",
    "shophive": "https://shophive.com",
    "yayvo": "https://www.yayvo.com",
    "symbios.pk": "https://symbios.pk",
    "goto.com.pk": "https://goto.com.pk",
    "homeshopping.pk": "https://homeshopping.pk",
    "ishopping.pk": "https://ishopping.pk",
    "mega.pk": "https://mega.pk",
    "sastaticket": "https://www.sastaticket.pk",
    "airsial": "https://www.airsial.com",
    "serene air": "https://www.sereneair.com",
    "bookme.pk": "https://bookme.pk",
    "careem pk": "https://www.careem.com/en-pk",
    "indrive": "https://indriver.com",
    "bykea": "https://bykea.com",
    "swvl": "https://swvl.com",
    "jazzcash": "https://www.jazzcash.com.pk",
    "easypaisa": "https://easypaisa.com.pk",
    "sadapay": "https://sadapay.pk",
    "nayapay": "https://nayapay.com",
    "meezan bank": "https://www.meezanbank.com",
    "hbl": "https://www.hbl.com",
    "ubl": "https://www.ubldigital.com",
    "mcb": "https://www.mcb.com.pk",
    "allied bank": "https://www.abl.com",
    "bank alfalah": "https://www.bankalfalah.com",
    "standard chartered pk": "https://www.sc.com/pk",
    "faysal bank": "https://www.faysalbank.com",
    "askari bank": "https://www.askaribank.com",
    "state bank of pakistan": "https://www.sbp.org.pk",
    "pakistan stock exchange": "https://www.psx.com.pk",
    "sbp epayments": "https://1link.net.pk",
    "zong": "https://www.zong.com.pk",
    "jazz": "https://jazz.com.pk",
    "ufone": "https://www.ufone.com",
    "telenor pakistan": "https://www.telenor.com.pk",
    "ptcl": "https://www.ptcl.com.pk",
    "nayatel": "https://www.nayatel.com",
    "stormfiber": "https://www.stormfiber.com",
    "pta": "https://www.pta.gov.pk",
    "wapda": "https://www.wapda.gov.pk",
    "k-electric": "https://www.ke.com.pk",
    "lesco": "https://www.lesco.gov.pk",
    "sui southern gas": "https://www.ssgc.com.pk",
    "sui northern gas": "https://www.sngpl.com.pk",
    "virtual university": "https://www.vu.edu.pk",
    "lums": "https://lums.edu.pk",
    "nust": "https://nust.edu.pk",
    "fast nu": "https://nu.edu.pk",
    "comsats": "https://www.comsats.edu.pk",
    "punjab university": "https://pu.edu.pk",
    "karachi university": "https://uok.edu.pk",
    "iba karachi": "https://www.iba.edu.pk",
    "giki": "https://giki.edu.pk",
    "uet lahore": "https://www.uet.edu.pk",
     "airbnb experiences": "https://www.airbnb.com/experiences",
    "google earth": "https://earth.google.com",
    "google news": "https://news.google.com",
    "google finance": "https://www.google.com/finance",
    "google trends": "https://trends.google.com",
    "google podcasts": "https://podcasts.google.com",
    "google arts and culture": "https://artsandculture.google.com",
    "google one": "https://one.google.com",
    "google play": "https://play.google.com",
    "apple app store": "https://www.apple.com/app-store",
    "apple id": "https://appleid.apple.com",
    "icloud": "https://www.icloud.com",
    "find my iphone": "https://www.icloud.com/find",
    "apple support": "https://support.apple.com",
    "samsung members": "https://www.samsung.com/members",
    "microsoft store": "https://www.microsoft.com/store",
    "xbox live": "https://www.xbox.com/live",
    "playstation network": "https://www.playstation.com/psn",
    "epic online services": "https://dev.epicgames.com",
    "steamdb": "https://steamdb.info",
    "protondb": "https://www.protondb.com",
    "howlongtobeat": "https://howlongtobeat.com",
    "metacritic games": "https://www.metacritic.com/game",
    "pcgamer": "https://www.pcgamer.com",
    "eurogamer": "https://www.eurogamer.net",
    "rock paper shotgun": "https://www.rockpapershotgun.com",
    "destructoid": "https://www.destructoid.com",
    "escapist magazine": "https://www.escapistmagazine.com",
    "giant bomb": "https://www.giantbomb.com",
    "speedrun.com": "https://www.speedrun.com",
    "twitchtracker": "https://twitchtracker.com",
    "streamlabs": "https://streamlabs.com",
    "obs project": "https://obsproject.com",
    "restream": "https://restream.io",
    "kick": "https://kick.com",
    "rumble": "https://rumble.com",
    "odysee": "https://odysee.com",
    "bitchute": "https://www.bitchute.com",
    "vimeo pro": "https://vimeo.com/pro",
    "wistia": "https://wistia.com",
    "brightcove": "https://www.brightcove.com",
    "jwplayer": "https://www.jwplayer.com",
    "kapwing": "https://www.kapwing.com",
    "clipchamp": "https://clipchamp.com",
    "invideo": "https://invideo.io",
    "descript": "https://www.descript.com",
    "veed.io": "https://www.veed.io",
    "capcut": "https://www.capcut.com",
    "filmora": "https://filmora.wondershare.com",
    "davinci resolve": "https://www.blackmagicdesign.com/products/davinciresolve",
    "final cut pro": "https://www.apple.com/final-cut-pro",
    "premiere pro": "https://www.adobe.com/products/premiere.html",
    "after effects": "https://www.adobe.com/products/aftereffects.html",
    "photoshop": "https://www.adobe.com/products/photoshop.html",
    "illustrator": "https://www.adobe.com/products/illustrator.html",
    "lightroom": "https://www.adobe.com/products/photoshop-lightroom.html",
    "indesign": "https://www.adobe.com/products/indesign.html",
    "xd": "https://www.adobe.com/products/xd.html",
    "sketch": "https://www.sketch.com",
    "framer": "https://www.framer.com",
    "invision": "https://www.invisionapp.com",
    "zeplin": "https://zeplin.io",
    "abstract": "https://www.abstract.com",
    "principle": "https://principleformac.com",
    "protopie": "https://www.protopie.io",
    "marvel app": "https://marvelapp.com",
    "balsamiq": "https://balsamiq.com",
    "axure": "https://www.axure.com",
    "justinmind": "https://www.justinmind.com",
    "uxpin": "https://www.uxpin.com",
    "maze": "https://maze.co",
    "usertesting": "https://www.usertesting.com",
    "hotjar": "https://www.hotjar.com",
    "fullstory": "https://www.fullstory.com",
    "mixpanel": "https://mixpanel.com",
    "amplitude": "https://amplitude.com",
    "google analytics": "https://analytics.google.com",
    "google tag manager": "https://tagmanager.google.com",
    "google search console": "https://search.google.com/search-console",
    "google ads": "https://ads.google.com",
    "facebook ads manager": "https://www.facebook.com/adsmanager",
    "semrush": "https://www.semrush.com",
    "ahrefs": "https://ahrefs.com",
    "moz": "https://moz.com",
    "ubersuggest": "https://neilpatel.com/ubersuggest",
    "screaming frog": "https://www.screamingfrog.co.uk",
    "buffer": "https://buffer.com",
    "hootsuite": "https://www.hootsuite.com",
    "sprout social": "https://sproutsocial.com",
    "later": "https://later.com",
    "canva pro": "https://www.canva.com/pro",
    "vistaprint": "https://www.vistaprint.com",
    "moo": "https://www.moo.com",
    "printful": "https://www.printful.com",
    "printify": "https://printify.com",
    "teespring": "https://www.teespring.com",
    "redbubble": "https://www.redbubble.com",
    "society6": "https://society6.com",
    "zazzle": "https://www.zazzle.com",
    "cafepress": "https://www.cafepress.com",
    "spreadshirt": "https://www.spreadshirt.com",
    "gumroad": "https://gumroad.com",
    "patreon": "https://www.patreon.com",
    "kickstarter": "https://www.kickstarter.com",
    "indiegogo": "https://www.indiegogo.com",
    "gofundme": "https://www.gofundme.com",
    "ko-fi": "https://ko-fi.com",
    "buymeacoffee": "https://www.buymeacoffee.com",
    "opencollective": "https://opencollective.com",
    "substack": "https://substack.com",
    "ghost": "https://ghost.org",
    "blogger": "https://www.blogger.com",
    "medium partner program": "https://medium.com/creators",
    "linktree": "https://linktr.ee",
    "beacons": "https://beacons.ai",
    "carrd": "https://carrd.co",
    "notion sites": "https://www.super.so",
    "google sites": "https://sites.google.com",
    "weebly": "https://www.weebly.com",
    "jimdo": "https://www.jimdo.com",
    "strikingly": "https://www.strikingly.com",
    "webs.com": "https://www.webs.com",
    "typeform": "https://www.typeform.com",
    "google forms": "https://forms.google.com",
    "surveymonkey": "https://www.surveymonkey.com",
    "jotform": "https://www.jotform.com",
    "formstack": "https://www.formstack.com",
    "wufoo": "https://www.wufoo.com",
    "qualtrics": "https://www.qualtrics.com",
    "zapier": "https://zapier.com",
    "make.com": "https://www.make.com",
    "ifttt": "https://ifttt.com",
    "n8n": "https://n8n.io",
    "airtable automations": "https://www.airtable.com/platform/automations",
    "retool": "https://retool.com",
    "bubble": "https://bubble.io",
    "glide": "https://www.glideapps.com",
    "adalo": "https://www.adalo.com",
    "flutterflow": "https://flutterflow.io",
    "expo": "https://expo.dev",
    "react native": "https://reactnative.dev",
    "flutter": "https://flutter.dev",
    "unity": "https://unity.com",
    "unreal engine": "https://www.unrealengine.com",
    "godot engine": "https://godotengine.org",
    "blender": "https://www.blender.org",
    "sketchfab": "https://sketchfab.com",
    "turbosquid": "https://www.turbosquid.com",
    "cgtrader": "https://www.cgtrader.com",
    "mixamo": "https://www.mixamo.com",
    "polyhaven": "https://polyhaven.com",
    "opengameart": "https://opengameart.org",
    "itch": "https://itch.io/game-assets",
    "humble bundle": "https://www.humblebundle.com",
    "fanatical": "https://www.fanatical.com",
    "green man gaming": "https://www.greenmangaming.com",
    "g2a": "https://www.g2a.com",
    "cdkeys": "https://www.cdkeys.com",
    "epicgames store": "https://store.epicgames.com",
    "playstation store": "https://store.playstation.com",
    "microsoft store games": "https://www.xbox.com/games",
    "nintendo eshop": "https://www.nintendo.com/store",
    "meta quest": "https://www.meta.com/quest",
    "oculus": "https://www.oculus.com",
    "steamvr": "https://store.steampowered.com/steamvr",
    "vrchat": "https://hello.vrchat.com",
    "rec room": "https://recroom.com",
    "second life": "https://secondlife.com",
    "decentraland": "https://decentraland.org",
    "the sandbox": "https://www.sandbox.game",
    "opensea": "https://opensea.io",
    "rarible": "https://rarible.com",
    "magic eden": "https://magiceden.io",
    "metamask": "https://metamask.io",
    "trust wallet": "https://trustwallet.com",
    "ledger": "https://www.ledger.com",
    "trezor": "https://trezor.io",
    "etherscan": "https://etherscan.io",
    "blockchain.com": "https://www.blockchain.com",
    "coindesk": "https://www.coindesk.com",
    "cointelegraph": "https://cointelegraph.com",
    "decrypt": "https://decrypt.co",
    "the block": "https://www.theblock.co",
    "messari": "https://messari.io",
    "defillama": "https://defillama.com",
    "uniswap": "https://uniswap.org",
    "pancakeswap": "https://pancakeswap.finance",
    "aave": "https://aave.com",
    "compound finance": "https://compound.finance",
    "opensea academy": "https://opensea.io/learn",
    "coinbase wallet": "https://www.coinbase.com/wallet",
    "gemini exchange": "https://www.gemini.com",
    "bitfinex": "https://www.bitfinex.com",
    "bitstamp": "https://www.bitstamp.net",
    "kucoin": "https://www.kucoin.com",
    "okx": "https://www.okx.com",
    "bybit": "https://www.bybit.com",
    "huobi": "https://www.htx.com",
    "gate.io": "https://www.gate.io",
    "crypto.com": "https://crypto.com",
    "metamask swap": "https://metamask.io/swaps",
    "chainlink": "https://chain.link",
    "polygon": "https://polygon.technology",
    "solana": "https://solana.com",
    "cardano": "https://cardano.org",
    "avalanche": "https://www.avax.network",
    "cosmos network": "https://cosmos.network",
    "polkadot": "https://polkadot.network",
    "near protocol": "https://near.org",
    "algorand": "https://algorand.com",
    "the graph": "https://thegraph.com",
    "arweave": "https://www.arweave.org",
    "filecoin": "https://filecoin.io",
    "ipfs": "https://ipfs.tech",
    "protocol labs": "https://protocol.ai",
    "ens domains": "https://ens.domains",
    "unstoppable domains": "https://unstoppabledomains.com",
    "brave browser": "https://brave.com",
    "firefox": "https://www.mozilla.org/firefox",
    "chrome": "https://www.google.com/chrome",
    "microsoft edge": "https://www.microsoft.com/edge",
    "opera browser": "https://www.opera.com",
    "vivaldi": "https://vivaldi.com",
    "tor browser": "https://www.torproject.org",
    "duckduckgo browser": "https://duckduckgo.com/app",
    "arc browser": "https://arc.net",
    "safari": "https://www.apple.com/safari",
    "fbise": "https://www.fbise.edu.pk",
    "fbi se": "https://www.fbise.edu.pk",
    "federal board": "https://www.fbise.edu.pk",
    "fbise result": "https://result.fbise.edu.pk",
    "fbise online": "https://online.fbise.edu.pk",
    "fbise portal": "https://portal.fbise.edu.pk",
    "fbise syllabus": "https://www.fbise.edu.pk",
    "fbise past papers": "https://www.fbise.edu.pk",
    "fbise date sheet": "https://www.fbise.edu.pk",
    "fbise model papers": "https://www.fbise.edu.pk",
    "ibcc": "https://ibcc.edu.pk",
    "ibcc attestation": "https://attest.ibcc.edu.pk",
    "nccs": "https://nccs.pk",
    "navttc": "https://navttc.gov.pk",
    "psdf": "https://www.psdf.org.pk",
    "sindh education": "https://www.sindheducation.gov.pk",
    "sindh board": "https://bsek.edu.pk",
    "bsek": "https://bsek.edu.pk",
    "biek": "https://biek.edu.pk",
    "karachi board": "https://biek.edu.pk",
    "punjab board": "https://biselahore.com",
    "biselahore": "https://biselahore.com",
    "kpk board": "https://www.bisess.edu.pk",
    "balochistan board": "https://bbise.edu.pk",
    "ajk board": "https://ajkbise.net",
    "higher education commission": "https://www.hec.gov.pk",
    "hec scholarships": "https://www.hec.gov.pk",
    "hec degree attestation": "https://eservices.hec.gov.pk",
    "ehsaas scholarship": "https://www.hec.gov.pk",
    "prime minister laptop scheme": "https://laptop.pmyp.gov.pk",
    "pakistan education": "https://www.moent.gov.pk",
    "ministry education pakistan": "https://www.moent.gov.pk",
    "national curriculum council": "https://ncc.gov.pk",
    "punjab education": "https://schools.punjab.gov.pk",
    "sindh education foundation": "https://www.sef.org.pk",
    "air university": "https://www.au.edu.pk",
    "comsats admissions": "https://admissions.comsats.edu.pk",
    "nust admissions": "https://ugadmissions.nust.edu.pk",
    "fast admissions": "https://admissions.nu.edu.pk",
    "iba admissions": "https://admissions.iba.edu.pk",
    "giki admissions": "https://giki.edu.pk",
    "bahria university": "https://www.bahria.edu.pk",
    "bahria admissions": "https://www.bahria.edu.pk",
    "szabist": "https://www.szabist.edu.pk",
    "habib university": "https://habib.edu.pk",
    "dha suffa university": "https://www.dsu.edu.pk",
    "ned university": "https://www.neduet.edu.pk",
    "ned admissions": "https://www.neduet.edu.pk",
    "sir syed university": "https://www.ssuet.edu.pk",
    "iqra university": "https://iqra.edu.pk",
    "islamia university": "https://www.iub.edu.pk",
    "university of peshawar": "https://www.uop.edu.pk",
    "university of karachi admissions": "https://www.uok.edu.pk",
    "dow university": "https://www.duhs.edu.pk",
    "aga khan university": "https://www.aku.edu",
    "lums admissions": "https://lums.edu.pk",
    "umt": "https://www.umt.edu.pk",
    "uol": "https://uol.edu.pk",
    "university of lahore": "https://uol.edu.pk",
    "superior university": "https://www.superior.edu.pk",
    "fast nuces": "https://nu.edu.pk",
    "mit opencourseware": "https://ocw.mit.edu",
    "mit": "https://www.mit.edu",
    "stanford online": "https://online.stanford.edu",
    "harvard online": "https://pll.harvard.edu",
    "yale courses": "https://oyc.yale.edu",
    "berkeley courses": "https://extension.berkeley.edu",
    "openlearn": "https://www.open.edu/openlearn",
    "alison": "https://alison.com",
    "futurelearn": "https://www.futurelearn.com",
    "saylor academy": "https://learn.saylor.org",
    "freecodecamp": "https://www.freecodecamp.org",
    "the odin project": "https://www.theodinproject.com",
    "full stack open": "https://fullstackopen.com",
    "roadmap.sh": "https://roadmap.sh",
    "frontend mentor": "https://www.frontendmentor.io",
    "scrimba": "https://scrimba.com",
    "mimo": "https://mimo.org",
    "sololearn": "https://www.sololearn.com",
    "programiz": "https://www.programiz.com",
    "tutorialspoint": "https://www.tutorialspoint.com",
    "educative": "https://www.educative.io",
    "datacamp": "https://www.datacamp.com",
    "brilliant": "https://brilliant.org",
    "ocw": "https://ocw.mit.edu",
    "w3 resource": "https://www.w3resource.com",
    "javascript": "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    "javascript info": "https://javascript.info",
    "typescript": "https://www.typescriptlang.org",
    "typescript docs": "https://www.typescriptlang.org/docs",
    "react": "https://react.dev",
    "react docs": "https://react.dev",
    "nextjs": "https://nextjs.org",
    "next js": "https://nextjs.org",
    "vue": "https://vuejs.org",
    "angular": "https://angular.dev",
    "svelte": "https://svelte.dev",
    "astro": "https://astro.build",
    "vite": "https://vite.dev",
    "webpack": "https://webpack.js.org",
    "babel": "https://babeljs.io",
    "eslint": "https://eslint.org",
    "prettier": "https://prettier.io",
    "npmjs": "https://www.npmjs.com",
    "yarn": "https://yarnpkg.com",
    "pnpm": "https://pnpm.io",
    "bun": "https://bun.sh",
    "deno": "https://deno.com",
    "nodejs": "https://nodejs.org",
    "node js": "https://nodejs.org",
    "express": "https://expressjs.com",
    "expressjs": "https://expressjs.com",
    "nestjs": "https://nestjs.com",
    "fastify": "https://fastify.dev",
    "hono": "https://hono.dev",
    "socket.io": "https://socket.io",
    "jquery": "https://jquery.com",
    "axios": "https://axios-http.com",
    "redux": "https://redux.js.org",
    "zustand": "https://zustand.docs.pmnd.rs",
    "tanstack": "https://tanstack.com",
    "react router": "https://reactrouter.com",
    "framer motion": "https://motion.dev",
    "threejs": "https://threejs.org",
    "three.js": "https://threejs.org",
    "web components": "https://developer.mozilla.org/en-US/docs/Web/API/Web_components",
    "css tricks": "https://css-tricks.com",
    "sass": "https://sass-lang.com",
    "less css": "https://lesscss.org",
    "bulma": "https://bulma.io",
    "material ui": "https://mui.com",
    "chakra ui": "https://chakra-ui.com",
    "shadcn": "https://ui.shadcn.com",
    "radix ui": "https://www.radix-ui.com",
    "daisyui": "https://daisyui.com",
    "headless ui": "https://headlessui.com",
    "ant design": "https://ant.design",
    "mantine": "https://mantine.dev",
    "semantic ui": "https://semantic-ui.com",
    "uiverse": "https://uiverse.io",
    "css gradient": "https://cssgradient.io",
    "getwaves": "https://getwaves.io",
    "haikei": "https://haikei.app",
    "fffuel": "https://www.fffuel.co",
    "css glass": "https://css.glass",
    "python": "https://www.python.org",
    "python docs": "https://docs.python.org",
    "python pypi": "https://pypi.org",
    "real python": "https://realpython.com",
    "python tutor": "https://pythontutor.com",
    "python package index": "https://pypi.org",
    "anaconda": "https://www.anaconda.com",
    "conda": "https://docs.conda.io",
    "jupyter": "https://jupyter.org",
    "jupyter notebook": "https://jupyter.org",
    "google colab": "https://colab.research.google.com",
    "numpy": "https://numpy.org",
    "pandas": "https://pandas.pydata.org",
    "matplotlib": "https://matplotlib.org",
    "scipy": "https://scipy.org",
    "scikit learn": "https://scikit-learn.org",
    "flask": "https://flask.palletsprojects.com",
    "django": "https://www.djangoproject.com",
    "fastapi": "https://fastapi.tiangolo.com",
    "beautiful soup": "https://www.crummy.com/software/BeautifulSoup",
    "selenium": "https://www.selenium.dev",
    "playwright": "https://playwright.dev",
    "cplusplus": "https://cplusplus.com",
    "cppreference": "https://en.cppreference.com",
    "c programming": "https://www.learn-c.org",
    "learn cpp": "https://www.learncpp.com",
    "java": "https://www.java.com",
    "java docs": "https://docs.oracle.com/en/java",
    "kotlin": "https://kotlinlang.org",
    "rust": "https://www.rust-lang.org",
    "rust docs": "https://doc.rust-lang.org",
    "go": "https://go.dev",
    "golang": "https://go.dev",
    "php": "https://www.php.net",
    "ruby": "https://www.ruby-lang.org",
    "dart": "https://dart.dev",
    "perl": "https://www.perl.org",
    "my github": "https://github.com/Wasayullah",
    "github explore": "https://github.com/explore",
    "github trending": "https://github.com/trending",
    "github gist": "https://gist.github.com",
    "github pages": "https://pages.github.com",
    "github actions": "https://github.com/features/actions",
    "github copilot": "https://github.com/features/copilot",
    "git": "https://git-scm.com",
    "git scm": "https://git-scm.com",
    "git documentation": "https://git-scm.com/docs",
    "gitlab docs": "https://docs.gitlab.com",
    "bitbucket docs": "https://support.atlassian.com/bitbucket",
    "sourcehut": "https://sr.ht",
    "gitea": "https://about.gitea.com",
    "codeberg": "https://codeberg.org",
    "opensource": "https://opensource.com",
    "mongodb": "https://www.mongodb.com",
    "mongodb atlas": "https://www.mongodb.com/atlas",
    "mongodb docs": "https://www.mongodb.com/docs",
    "mysql": "https://www.mysql.com",
    "mysql docs": "https://dev.mysql.com/doc",
    "postgresql": "https://www.postgresql.org",
    "postgres docs": "https://www.postgresql.org/docs",
    "sqlite": "https://sqlite.org",
    "redis": "https://redis.io",
    "redis docs": "https://redis.io/docs",
    "firebase": "https://firebase.google.com",
    "firebase console": "https://console.firebase.google.com",
    "supabase": "https://supabase.com",
    "supabase docs": "https://supabase.com/docs",
    "appwrite": "https://appwrite.io",
    "pocketbase": "https://pocketbase.io",
    "planetscale": "https://planetscale.com",
    "neon": "https://neon.tech",
    "cockroachdb": "https://www.cockroachlabs.com",
    "prisma": "https://www.prisma.io",
    "drizzle": "https://orm.drizzle.team",
    "sequelize": "https://sequelize.org",
    "postman api": "https://www.postman.com",
    "swagger": "https://swagger.io",
    "openapi": "https://www.openapis.org",
    "rapidapi": "https://rapidapi.com",
    "render": "https://render.com",
    "railway": "https://railway.app",
    "fly.io": "https://fly.io",
    "firebase hosting": "https://firebase.google.com/products/hosting",
    "github pages": "https://pages.github.com",
    "aws console": "https://console.aws.amazon.com",
    "aws documentation": "https://docs.aws.amazon.com",
    "azure portal": "https://portal.azure.com",
    "azure docs": "https://learn.microsoft.com/azure",
    "google cloud console": "https://console.cloud.google.com",
    "google cloud docs": "https://cloud.google.com/docs",
    "cloudflare pages": "https://pages.cloudflare.com",
    "cloudflare workers": "https://workers.cloudflare.com",
    "digital ocean docs": "https://docs.digitalocean.com",
    "vercel dashboard": "https://vercel.com/dashboard",
    "netlify dashboard": "https://app.netlify.com",
    "heroku dashboard": "https://dashboard.heroku.com",
    "nginx": "https://nginx.org",
    "apache": "https://httpd.apache.org",
    "tryhackme": "https://tryhackme.com",
    "hack the box": "https://www.hackthebox.com",
    "hackthebox academy": "https://academy.hackthebox.com",
    "portswigger": "https://portswigger.net",
    "portswigger academy": "https://portswigger.net/web-security",
    "owasp": "https://owasp.org",
    "owasp top 10": "https://owasp.org/www-project-top-ten",
    "exploit db": "https://www.exploit-db.com",
    "cve": "https://cve.org",
    "nvd": "https://nvd.nist.gov",
    "mitre attack": "https://attack.mitre.org",
    "mitre": "https://www.mitre.org",
    "sans institute": "https://www.sans.org",
    "cybrary": "https://www.cybrary.it",
    "picoctf": "https://picoctf.org",
    "ctftime": "https://ctftime.org",
    "over the wire": "https://overthewire.org",
    "bandit": "https://overthewire.org/wargames/bandit",
    "root me": "https://www.root-me.org",
    "vulnhub": "https://www.vulnhub.com",
    "pentesterlab": "https://pentesterlab.com",
    "security blue team": "https://securityblue.team",
    "hackviser": "https://hackviser.com",
    "kali linux": "https://www.kali.org",
    "kali tools": "https://www.kali.org/tools",
    "parrot os": "https://www.parrotsec.org",
    "wireshark": "https://www.wireshark.org",
    "nmap": "https://nmap.org",
    "metasploit": "https://www.metasploit.com",
    "burp suite": "https://portswigger.net/burp",
    "john the ripper": "https://www.openwall.com/john",
    "hashcat": "https://hashcat.net",
    "aircrack ng": "https://www.aircrack-ng.org",
    "pytorch": "https://pytorch.org",
    "tensorflow": "https://www.tensorflow.org",
    "keras": "https://keras.io",
    "hugging face": "https://huggingface.co",
    "huggingface models": "https://huggingface.co/models",
    "huggingface datasets": "https://huggingface.co/datasets",
    "huggingface spaces": "https://huggingface.co/spaces",
    "openai platform": "https://platform.openai.com",
    "openai docs": "https://platform.openai.com/docs",
    "anthropic": "https://www.anthropic.com",
    "anthropic docs": "https://docs.anthropic.com",
    "google ai studio": "https://aistudio.google.com",
    "gemini api": "https://ai.google.dev",
    "ollama": "https://ollama.com",
    "lm studio": "https://lmstudio.ai",
    "replicate": "https://replicate.com",
    "together ai": "https://www.together.ai",
    "groq": "https://groq.com",
    "mistral ai": "https://mistral.ai",
    "deepseek api": "https://platform.deepseek.com",
    "langchain": "https://www.langchain.com",
    "langchain docs": "https://python.langchain.com",
    "llamaindex": "https://www.llamaindex.ai",
    "pinecone": "https://www.pinecone.io",
    "weaviate": "https://weaviate.io",
    "chroma": "https://www.trychroma.com",
    "faiss": "https://faiss.ai",
    "weights and biases": "https://wandb.ai",
    "kaggle datasets": "https://www.kaggle.com/datasets",
    "papers with code": "https://paperswithcode.com",
    "linear": "https://linear.app",
    "plane": "https://plane.so",
    "basecamp": "https://basecamp.com",
    "height": "https://height.app",
    "youtrack": "https://www.jetbrains.com/youtrack",
    "sourcegraph": "https://sourcegraph.com",
    "cursor": "https://cursor.com",
    "windsurf": "https://windsurf.com",
    "vscode": "https://code.visualstudio.com",
    "visual studio code": "https://code.visualstudio.com",
    "vs code": "https://code.visualstudio.com",
    "jetbrains academy": "https://www.jetbrains.com/academy",
    "github codespaces": "https://github.com/features/codespaces",
    "stackblitz": "https://stackblitz.com",
    "codesandbox": "https://codesandbox.io",
    "glitch": "https://glitch.com",
    "replit workspace": "https://replit.com",
    "gitpod": "https://www.gitpod.io",
    "insomnia": "https://insomnia.rest",
    "hoppscotch": "https://hoppscotch.io",
    "httpbin": "https://httpbin.org",
    "reqres": "https://reqres.in",
    "mockapi": "https://mockapi.io",
    "jsonplaceholder": "https://jsonplaceholder.typicode.com",
    "rest countries": "https://restcountries.com",
    "public apis": "https://publicapis.dev",
    "public apis list": "https://github.com/public-apis/public-apis",
    "rapidapi marketplace": "https://rapidapi.com/hub",
    "mdn web docs": "https://developer.mozilla.org",
    "web dev": "https://web.dev",
    "developer chrome": "https://developer.chrome.com",
    "developer mozilla": "https://developer.mozilla.org",
    "can i use": "https://caniuse.com",
    "devdocs": "https://devdocs.io",
    "devhints": "https://devhints.io",
    "overapi": "https://overapi.com",
    "readme": "https://readme.com",
    "gitbook": "https://www.gitbook.com",
    "read the docs": "https://readthedocs.org",
    "docusaurus": "https://docusaurus.io",
    "vitepress": "https://vitepress.dev",
    "cp algorithms": "https://cp-algorithms.com",
    "algorithm visualizer": "https://algorithm-visualizer.org",
    "visualgo": "https://visualgo.net",
    "big o cheat sheet": "https://www.bigocheatsheet.com",
    "geeksforgeeks algorithms": "https://www.geeksforgeeks.org/algorithms",
    "leetcode discuss": "https://leetcode.com/discuss",
    "codeforces gym": "https://codeforces.com/gyms",
    "atcoder": "https://atcoder.jp",
    "codingame": "https://www.codingame.com",
    "dmoj": "https://dmoj.ca",
    "kattis": "https://open.kattis.com",
    "beecrowd": "https://www.beecrowd.com.br",
    "wolfram alpha": "https://www.wolframalpha.com",
    "desmos": "https://www.desmos.com",
    "geogebra": "https://www.geogebra.org",
    "symbolab": "https://www.symbolab.com",
    "mathway": "https://www.mathway.com",
    "brilliant math": "https://brilliant.org/courses/math",
    "paul's online math notes": "https://tutorial.math.lamar.edu",
    "math stackexchange": "https://math.stackexchange.com",
    "physics stackexchange": "https://physics.stackexchange.com",
    "chemistry stackexchange": "https://chemistry.stackexchange.com",
    "science alert": "https://www.sciencealert.com",
    "khan physics": "https://www.khanacademy.org/science/physics",
    "hyperphysics": "http://hyperphysics.phy-astr.gsu.edu",
    "cambridge dictionary": "https://dictionary.cambridge.org",
    "oxford dictionary": "https://www.oxfordlearnersdictionaries.com",
    "collins dictionary": "https://www.collinsdictionary.com",
    "ludwig": "https://ludwig.guru",
    "quillbot": "https://quillbot.com",
    "hemingway editor": "https://hemingwayapp.com",
    "prowritingaid": "https://prowritingaid.com",
    "language tool": "https://languagetool.org",
    "wordreference": "https://www.wordreference.com",
    "quran.com": "https://quran.com",
    "quran": "https://quran.com",
    "sunnah.com": "https://sunnah.com",
    "islamqa": "https://islamqa.info",
    "islamweb": "https://www.islamweb.net",
    "altafsir": "https://www.altafsir.com",
    "tanzil": "https://tanzil.net",
    "corpus quran": "https://corpus.quran.com",
    "quranic arabic corpus": "https://corpus.quran.com",
    "arabic keyboard": "https://www.lexilogos.com/keyboard/arabic.htm",
    "arabic lexicon": "https://www.arabic-lexicon.com",
    "almaany": "https://www.almaany.com",
    "arabdict": "https://www.arabdict.com",
    "reverso": "https://context.reverso.net",
    "google classroom": "https://classroom.google.com",
    "microsoft onenote": "https://www.onenote.com",
    "notebooklm": "https://notebooklm.google.com",
    "obsidian publish": "https://obsidian.md",
    "evernote web": "https://www.evernote.com",
    "notion templates": "https://www.notion.so/templates",
    "google tasks": "https://tasks.google.com",
    "microsoft todo": "https://to-do.office.com",
    "forest": "https://www.forestapp.cc",
    "pomofocus": "https://pomofocus.io",
    "clockify": "https://clockify.me",
    "toggl": "https://toggl.com",
    "ilovepdf": "https://www.ilovepdf.com",
    "smallpdf": "https://smallpdf.com",
    "pdfescape": "https://www.pdfescape.com",
    "sejda": "https://www.sejda.com",
    "remove bg": "https://www.remove.bg",
    "tinypng": "https://tinypng.com",
    "tinyjpg": "https://tinyjpg.com",
    "squoosh": "https://squoosh.app",
    "cloudconvert": "https://cloudconvert.com",
    "convertio": "https://convertio.co",
    "exiftool": "https://exiftool.org",
    "regex tester": "https://regex101.com",
    "json viewer": "https://jsonviewer.stack.hu",
    "json crack": "https://jsoncrack.com",
    "jwt debugger": "https://jwt.io",
    "jwt io": "https://jwt.io",
    "url encoder": "https://www.urlencoder.org",
    "url decoder": "https://www.urldecoder.org",
    "chrome devtools": "https://developer.chrome.com/docs/devtools",
    "firefox developer": "https://developer.mozilla.org",
    "webpagetest": "https://www.webpagetest.org",
    "pagespeed insights": "https://pagespeed.web.dev",
    "gtmetrix": "https://gtmetrix.com",
    "lighthouse": "https://developer.chrome.com/docs/lighthouse",
    "validator w3": "https://validator.w3.org",
    "html validator": "https://validator.w3.org",
    "css validator": "https://jigsaw.w3.org/css-validator",
    "github jobs": "https://github.com",
    "linkedin jobs": "https://www.linkedin.com/jobs",
    "indeed jobs": "https://www.indeed.com",
    "upwork jobs": "https://www.upwork.com/nx/jobs",
    "fiverr gigs": "https://www.fiverr.com",
    "freelancer jobs": "https://www.freelancer.com",
    "contra": "https://contra.com",
    "turing": "https://www.turing.com",
    "remoteok": "https://remoteok.com",
    "we work remotely": "https://weworkremotely.com",
    "wellfound": "https://wellfound.com",
    "levels.fyi": "https://www.levels.fyi",
    "roadmap": "https://roadmap.sh",
    "hackernews": "https://news.ycombinator.com",
    "lobsters": "https://lobste.rs",
    "slashdot": "https://slashdot.org",
    "dev community": "https://dev.to",
    "hashnode blogs": "https://hashnode.com",
    "daily dev": "https://app.daily.dev",
    "indie hackers": "https://www.indiehackers.com",
    "product hunt": "https://www.producthunt.com",
    "tech blogs": "https://dev.to",
    "github awesome": "https://github.com/sindresorhus/awesome",
    "awesome python": "https://github.com/vinta/awesome-python",
    "awesome javascript": "https://github.com/sorrycc/awesome-javascript",
    "awesome react": "https://github.com/enaqx/awesome-react",
    "public apis github": "https://github.com/public-apis/public-apis",
    "free for dev": "https://free-for.dev",
    "build your own x": "https://github.com/codecrafters-io/build-your-own-x",
    "coding projects": "https://github.com/practical-tutorials/project-based-learning",
    "project based learning": "https://github.com/practical-tutorials/project-based-learning",
    "vercel domains": "https://vercel.com/domains",
    "cloudflare dns": "https://www.cloudflare.com/dns",
    "namecheap domains": "https://www.namecheap.com/domains",
    "godaddy domains": "https://www.godaddy.com/domains",
    "freedns": "https://freedns.afraid.org",
    "noip": "https://www.noip.com",
    "dns checker": "https://dnschecker.org",
    "dns propagation": "https://www.whatsmydns.net",
    "ssl labs": "https://www.ssllabs.com/ssltest",
    "letsencrypt": "https://letsencrypt.org",
    "pcpartpicker": "https://pcpartpicker.com",
    "cpu benchmark": "https://www.cpubenchmark.net",
    "gpu benchmark": "https://www.videocardbenchmark.net",
    "techpowerup": "https://www.techpowerup.com",
    "notebookcheck": "https://www.notebookcheck.net",
    "tom's hardware": "https://www.tomshardware.com",
    "linus tech tips": "https://www.lttlabs.com",
    "ifixit": "https://www.ifixit.com",
    "microsoft learn": "https://learn.microsoft.com",
    "windows dev center": "https://developer.microsoft.com/windows",
    "windows terminal": "https://learn.microsoft.com/windows/terminal",
    "powershell": "https://learn.microsoft.com/powershell",
    "powershell gallery": "https://www.powershellgallery.com",
    "ubuntu": "https://ubuntu.com",
    "ubuntu docs": "https://documentation.ubuntu.com",
    "debian": "https://www.debian.org",
    "arch linux": "https://archlinux.org",
    "arch wiki": "https://wiki.archlinux.org",
    "linux kernel": "https://www.kernel.org",
    "linux journey": "https://linuxjourney.com",
    "distrowatch": "https://distrowatch.com",
    "virtualbox": "https://www.virtualbox.org",
    "vmware": "https://www.vmware.com",
    "wsl": "https://learn.microsoft.com/windows/wsl",
    "arduino": "https://www.arduino.cc",
    "arduino docs": "https://docs.arduino.cc",
    "raspberry pi": "https://www.raspberrypi.com",
    "raspberry pi docs": "https://www.raspberrypi.com/documentation",
    "esp32": "https://www.espressif.com",
    "platformio": "https://platformio.org",
    "microchip": "https://www.microchip.com",
    "electronics stackexchange": "https://electronics.stackexchange.com",
    "hackaday": "https://hackaday.com",
    "figma community": "https://www.figma.com/community",
    "figma resources": "https://www.figma.com/community/resources",
    "dribbble shots": "https://dribbble.com/shots",
    "behance discover": "https://www.behance.net",
    "awwwards": "https://www.awwwards.com",
    "css design awards": "https://www.cssdesignawards.com",
    "siteinspire": "https://www.siteinspire.com",
    "godly website": "https://godly.website",
    "lapa ninja": "https://www.lapa.ninja",
    "one page love": "https://onepagelove.com",
    "land book": "https://land-book.com",
    "font pair": "https://www.fontpair.co",
    "fontjoy": "https://fontjoy.com",
    "google icons": "https://fonts.google.com/icons",
    "heroicons": "https://heroicons.com",
    "lucide": "https://lucide.dev",
    "simple icons": "https://simpleicons.org",
    "svgrepo": "https://www.svgrepo.com",
    "iconify": "https://iconify.design",
    "pexels videos": "https://www.pexels.com/videos",
    "pixabay videos": "https://pixabay.com/videos",
    "coverr": "https://coverr.co",
    "mixkit": "https://mixkit.co",
    "videvo": "https://www.videvo.net",
    "freepik": "https://www.freepik.com",
    "vecteezy": "https://www.vecteezy.com",
    "unDraw": "https://undraw.co",
    "storyset": "https://storyset.com",
    "blush": "https://blush.design",
    "lordicon": "https://lordicon.com",
    "lottiefiles": "https://lottiefiles.com",
    "sentry": "https://sentry.io",
    "logrocket": "https://logrocket.com",
    "betterstack": "https://betterstack.com",
    "uptimerobot": "https://uptimerobot.com",
    "statuspage": "https://www.atlassian.com/software/statuspage",
    "posthog": "https://posthog.com",
    "plausible analytics": "https://plausible.io",
    "umami analytics": "https://umami.is",
    "google recaptcha": "https://www.google.com/recaptcha",
    "cloudinary": "https://cloudinary.com",
    "imgbb": "https://imgbb.com",
    "imgur api": "https://api.imgur.com",
    "uploadcare": "https://uploadcare.com",
    "resend": "https://resend.com",
    "sendgrid": "https://sendgrid.com",
    "mailgun": "https://www.mailgun.com",
    "stack overflow": "https://stackoverflow.com",
    "super user": "https://superuser.com",
    "ask ubuntu": "https://askubuntu.com",
    "server fault": "https://serverfault.com",
    "software engineering stackexchange": "https://softwareengineering.stackexchange.com",
    "code review stackexchange": "https://codereview.stackexchange.com",
    "cs stackexchange": "https://cs.stackexchange.com",
    "ai stackexchange": "https://ai.stackexchange.com",
    "security stackexchange": "https://security.stackexchange.com",
    "devops stackexchange": "https://devops.stackexchange.com",
    "webmasters stackexchange": "https://webmasters.stackexchange.com",
}


# =====================================================================
# WEBSITE CATEGORIES (for UI browsing)
# =====================================================================
WEBSITE_CATEGORIES = {
    'Social Media': ['facebook','twitter','instagram','tiktok','snapchat','pinterest','linkedin','reddit','discord','telegram','whatsapp','threads'],
    'Search Engines': ['google','bing','yahoo','duckduckgo','baidu','yandex','ecosia'],
    'Video & Streaming': ['youtube','netflix','twitch','hulu','disney plus','spotify','apple music','soundcloud','vimeo','dailymotion','crunchyroll'],
    'AI Tools': ['chatgpt','claude','gemini','copilot','perplexity','deepseek','grok','openai','huggingface','midjourney','poe'],
    'Dev & Code': ['github','gitlab','stackoverflow','leetcode','hackerrank','replit','codepen','w3schools','mdn','freecodecamp','vercel','netlify','docker','pypi','npm'],
    'News': ['cnn','bbc','reuters','al jazeera','the verge','techcrunch','engadget','wired','ars technica','dawn','geo news'],
    'Shopping': ['amazon','ebay','aliexpress','etsy','walmart','target','flipkart','daraz','shein','temu'],
    'Education': ['coursera','udemy','khan academy','edx','duolingo','google scholar','arxiv','brilliant'],
    'Cloud & DevOps': ['aws','azure','google cloud','digitalocean','heroku','vercel','cloudflare','firebase','supabase','kubernetes','dockerhub'],
    'Travel': ['booking.com','airbnb','expedia','tripadvisor','uber','lyft','google flights','skyscanner'],
    'Finance': ['paypal','coinbase','binance','robinhood','chase','wise','venmo'],
    'Pakistan': ['daraz','olx pakistan','zameen','jazzcash','easypaisa','fbise','nust','lums','fast nu','comsats','hbl','mcb'],
    'Games': ['steam','epic games','playstation','xbox','nintendo','roblox','chess.com','lichess'],
    'Streaming Video': ['netflix','hulu','disney plus','amazon prime video','hbo max','peacock','crunchyroll'],
}
